version: '3'
services:
    app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: 'www-data'
        volumes:
            - '.:/var/www/html'
        networks:
            - jumia
networks:
    jumia:
        driver: bridge
volumes:
    jumia_db:
        driver: local
